"""empty message

Revision ID: 492a94269059
Revises: 71c8e4a4270e
Create Date: 2019-07-30 21:43:13.616164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '492a94269059'
down_revision = '71c8e4a4270e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('client_key', table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_key', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('client_secret', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('client_key', 'client', ['client_key'], unique=True)
    # ### end Alembic commands ###
