"""empty message

Revision ID: 71c8e4a4270e
Revises: 
Create Date: 2019-07-30 19:19:02.178046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c8e4a4270e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sex', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sex', 'person', ['sex'], unique=True)
    # ### end Alembic commands ###
