"""empty message

Revision ID: 829f12185f0c
Revises: 492a94269059
Create Date: 2019-07-30 22:06:47.724480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829f12185f0c'
down_revision = '492a94269059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'users', ['name'], unique=True)
    # ### end Alembic commands ###
